### ISSUE TITLE
[zod-openapi] Return value of `c.get(…)` is of type `never` after updating to v0.17.0

### ISSUE THREAD

**Issue by marvinruder** [honojs/middleware#814]
Given the type declaration

```
declare module "hono" {
  interface ContextVariableMap {
    user: { email: string };
  }
}
```

when using `c.get("user").email` within a `new OpenAPIHono().openapi(…)` handler then TypeScript shows the type error `Property 'email' does not exist on type 'never'`. Autocompletion for the string `user` still works, but `c.get("user")` is of type `never`.

**Comment by yusukebe** [comment]
@marvinruder @oberbeck Okay. I'll close this issue. Thanks.
